### PR TITLE
Remove complicated webpack setup, replace with esbuild

### PR DESCRIPTION
**Pull request by ahmed-musallam**
- Remove webpack, use esbuild - Much faster and easier to use
- introduce a script for faster express js up time using esbuild
- remove a lot of unwanted/unused dependencies

Overall, this speeds build time and disambiguates the build process.

### CODE REVIEW

**Comment by ahmed-musallam** [comment]
@Sivaramvt could you please review this if everything looks good to you let's merge it

**Comment by noormd08** [comment]
> Thanks @ahmed-musallam . Looks good to me. Am not proficient in FE build system though. Let me request @noormd08 to take a look and merge.

@ahmed-musallam Build command is successful and faster. However npm run serve is failing in Windows. 

image

**Review by noormd08 — CHANGES_REQUESTED** [review]
Please check the comments

**Comment by ahmed-musallam** [comment]
@noormd08 ahh I see the issue, will take a look

**Pull request merged**
